admin_homepage:
    path:     /
    defaults: { _controller: IndraAdminBundle:Admin:index }

admin_vote:
    path:     /votes
    defaults: { _controller: IndraAdminBundle:Admin:votes }

employe:
    resource: "@IndraAdminBundle/Resources/config/routing/employe.yml"
    prefix:   /

poste:
    resource: "@IndraAdminBundle/Resources/config/routing/poste.yml"
    prefix:   /

service:
    resource: "@IndraAdminBundle/Resources/config/routing/service.yml"
    prefix:   /


avance_salaire:
    resource: "@IndraAdminBundle/Resources/config/routing/avance_salaire.yml"
    prefix:   /

demande_permission:
    resource: "@IndraAdminBundle/Resources/config/routing/demande_permission.yml"
    prefix:   /

sanction:
    resource: "@IndraAdminBundle/Resources/config/routing/sanction.yml"
    prefix:   /

presence:
    resource: "@IndraAdminBundle/Resources/config/routing/presence.yml"
    prefix:   /

prime:
    resource: "@IndraAdminBundle/Resources/config/routing/prime.yml"
    prefix:   /

fiche_de_paie:
    resource: "@IndraAdminBundle/Resources/config/routing/fiche_de_paie.yml"
    prefix:   /

contrat:
    resource: "@IndraAdminBundle/Resources/config/routing/contrat.yml"
    prefix:   /

reunion:
    resource: "@IndraAdminBundle/Resources/config/routing/reunion.yml"
    prefix:   /

depense:
    resource: "@IndraAdminBundle/Resources/config/routing/depense.yml"
    prefix:   /

periodedepense:
    resource: "@IndraAdminBundle/Resources/config/routing/periodedepense.yml"
    prefix:   /

operation:
    resource: "@IndraAdminBundle/Resources/config/routing/operation.yml"
    prefix:   /

facture:
    resource: "@IndraAdminBundle/Resources/config/routing/facture.yml"
    prefix:   /

periodefacture:
    resource: "@IndraAdminBundle/Resources/config/routing/periodefacture.yml"
    prefix:   /

data:
    resource: "@IndraAdminBundle/Resources/config/routing/data.yml"
    prefix:   /

comptabilite:
    resource: "@IndraAdminBundle/Resources/config/routing/comptabilite.yml"
    prefix:   /

stock:
    resource: "@IndraAdminBundle/Resources/config/routing/stock.yml"
    prefix:   /

mouvementstock:
    resource: "@IndraAdminBundle/Resources/config/routing/mouvementstock.yml"
    prefix:   /

periodestock:
    resource: "@IndraAdminBundle/Resources/config/routing/periodestock.yml"
    prefix:   /

materiel:
    resource: "@IndraAdminBundle/Resources/config/routing/materiel.yml"
    prefix:   /

chambre:
    resource: "@IndraAdminBundle/Resources/config/routing/chambre.yml"
    prefix:   /

reservation:
    resource: "@IndraAdminBundle/Resources/config/routing/reservation.yml"
    prefix:   /

contact:
    resource: "@IndraAdminBundle/Resources/config/routing/contact.yml"
    prefix:   /

client:
    resource: "@IndraAdminBundle/Resources/config/routing/client.yml"
    prefix:   /

facture_reception:
    resource: "@IndraAdminBundle/Resources/config/routing/facture_reception.yml"
    prefix:   /

facturebarrestaurant:
    resource: "@IndraAdminBundle/Resources/config/routing/facturebarrestaurant.yml"
    prefix:   /