indra_client_homepage:
    path:     /
    defaults: { _controller: IndraClientBundle:Home:index }

chambre:
    resource: "@IndraClientBundle/Resources/config/routing/chambre.yml"
    prefix:   /

reservation:
    resource: "@IndraClientBundle/Resources/config/routing/reservation.yml"
    prefix:   /

contact:
    resource: "@IndraClientBundle/Resources/config/routing/contact.yml"
    prefix:   /

blog:
    resource: "@IndraClientBundle/Resources/config/routing/blog.yml"
    prefix:   /