indra_client_homepage:
    path:     /
    defaults: { _controller: IndraClientBundle:Home:index }

indra_client_lastArticle:
    path:     /last
    defaults: { _controller: IndraClientBundle:Home:lastArticle }

chambre:
    resource: "@IndraClientBundle/Resources/config/routing/chambre.yml"
    prefix:   /

reservation:
    resource: "@IndraClientBundle/Resources/config/routing/reservation.yml"
    prefix:   /

rating:
    resource: "@IndraClientBundle/Resources/config/routing/rating.yml"
    prefix:   /

contact:
    resource: "@IndraClientBundle/Resources/config/routing/contact.yml"
    prefix:   /

blog:
    resource: "@IndraClientBundle/Resources/config/routing/blog.yml"
    prefix:   /

resto_bar:
    resource: "@IndraClientBundle/Resources/config/routing/resto_bar.yml"
    prefix:   /

indra_client_about:
    path:     /a-propos-de-nous
    defaults: { _controller: IndraClientBundle:About:index }
