indra_client:
    resource: "@IndraClientBundle/Resources/config/routing.yml"
    prefix:   /

#janet_transit_admin:
#    resource: "@JanetTransitAdminBundle/Resources/config/routing.yml"
#    prefix:   /{_locale}
#    requirements:
#        _locale: en|fr
#
#janet_transit_wiki:
#    resource: "@JanetTransitWikiBundle/Resources/config/routing.yml"
#    prefix:   /{_locale}
#    requirements:
#        _locale: en|fr


indra_admin:
    resource: "@IndraAdminBundle/Resources/config/routing.yml"
    prefix:   /backoffice


indra_wiki:
    resource: "@IndraWikiBundle/Resources/config/routing.yml"
    prefix:   /backoffice

#    prefix:   /{_locale}
#    requirements:
#        _locale: en|fr

sonata_admin:
    resource: "sonata/routing/admin.yml"
    prefix:   /

sonata_media:
    resource: "sonata/routing/media.yml"
    prefix:   /

sonata_user:
    resource: "sonata/routing/user.yml"
    prefix:   /


#FOSJsRoutingBundle pour l'appel des routes dans le JS
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

