# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.category:
        class: Indra\WikiBundle\Admin\CategoryAdmin
        arguments: [~, Indra\WikiBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: WIKI, label: Category }

    admin.article:
        class: Indra\WikiBundle\Admin\ArticleAdmin
        arguments: [~, Indra\WikiBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: WIKI, label: Article }

    admin.poste:
        class: Indra\AdminBundle\Admin\PosteAdmin
        arguments: [~, Indra\AdminBundle\Entity\Poste, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Poste }

    admin.service:
        class: Indra\AdminBundle\Admin\ServiceAdmin
        arguments: [~, Indra\AdminBundle\Entity\Service, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Service }

    admin.avancesalaire:
        class: Indra\AdminBundle\Admin\AvanceSalaireAdmin
        arguments: [~, Indra\AdminBundle\Entity\AvanceSalaire, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Avance de Salaire }

    admin.demandepermission:
        class: Indra\AdminBundle\Admin\DemandePermissionAdmin
        arguments: [~, Indra\AdminBundle\Entity\DemandePermission, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Demande de Permission }

    admin.employe:
        class: Indra\AdminBundle\Admin\EmployeAdmin
        arguments: [~, Indra\AdminBundle\Entity\Employe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Employés }

    admin.presence:
        class: Indra\AdminBundle\Admin\PresenceAdmin
        arguments: [~, Indra\AdminBundle\Entity\Presence, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Présence & Absence }

    admin.fichedepaie:
        class: Indra\AdminBundle\Admin\FicheDePaieAdmin
        arguments: [~, Indra\AdminBundle\Entity\FicheDePaie, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Fiches de paie }

    admin.prime:
        class: Indra\AdminBundle\Admin\PrimeAdmin
        arguments: [~, Indra\AdminBundle\Entity\Prime, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Primes }

    admin.sanction:
        class: Indra\AdminBundle\Admin\SanctionAdmin
        arguments: [~, Indra\AdminBundle\Entity\Sanction, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Sanctions }

    admin.typecontrat:
        class: Indra\AdminBundle\Admin\TypeContratAdmin
        arguments: [~, Indra\AdminBundle\Entity\TypeContrat, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Types de Contrat }

    admin.contrat:
        class: Indra\AdminBundle\Admin\ContratAdmin
        arguments: [~, Indra\AdminBundle\Entity\Contrat, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: EMPLOYES, label: Contrats }

    admin.reunion:
        class: Indra\AdminBundle\Admin\ReunionAdmin
        arguments: [~, Indra\AdminBundle\Entity\Reunion, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: REUNION, label: Reunion}

    admin.typeDepense:
        class: Indra\AdminBundle\Admin\TypeDepenseAdmin
        arguments: [~, Indra\AdminBundle\Entity\TypeDepense, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DEPENSES, label: Type de Dépenses}

    admin.periodeDepense:
        class: Indra\AdminBundle\Admin\PeriodeDepenseAdmin
        arguments: [~, Indra\AdminBundle\Entity\PeriodeDepense, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DEPENSES, label: Journées des Dépenses}

    admin.depense:
        class: Indra\AdminBundle\Admin\DepenseAdmin
        arguments: [~, Indra\AdminBundle\Entity\Depense, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DEPENSES, label: Dépenses}

    admin.data:
        class: Indra\AdminBundle\Admin\DataAdmin
        arguments: [~, Indra\AdminBundle\Entity\Data, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DONNEES, label: Fichiers}

    admin.perdiodeFacture:
        class: Indra\AdminBundle\Admin\PeriodeFactureAdmin
        arguments: [~, Indra\AdminBundle\Entity\PeriodeFacture, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: MANUTENTION, label: Périodes}

    admin.facture:
        class: Indra\AdminBundle\Admin\FactureAdmin
        arguments: [~, Indra\AdminBundle\Entity\Facture, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: MANUTENTION, label: Factures}

    admin.typeStock:
        class: Indra\AdminBundle\Admin\TypeStockAdmin
        arguments: [~, Indra\AdminBundle\Entity\TypeStock, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: STOCK, label: Type de Stock}

    admin.periodeStock:
        class: Indra\AdminBundle\Admin\PeriodeStockAdmin
        arguments: [~, Indra\AdminBundle\Entity\PeriodeStock, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: STOCK, label: Journée de Mouvement}

    admin.stock:
        class: Indra\AdminBundle\Admin\StockAdmin
        arguments: [~, Indra\AdminBundle\Entity\Stock, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: STOCK, label: Stock}

    admin.mouvementStock:
        class: Indra\AdminBundle\Admin\MouvementStockAdmin
        arguments: [~, Indra\AdminBundle\Entity\MouvementStock, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: STOCK, label: Mouvements de Stock}

    admin.materiel:
        class: Indra\AdminBundle\Admin\MaterielAdmin
        arguments: [~, Indra\AdminBundle\Entity\Materiel, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: MATERIEL FORUNI, label: Matériels}

    admin.chambre:
        class: Indra\AdminBundle\Admin\ChambreAdmin
        arguments: [~, Indra\AdminBundle\Entity\Chambre, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: RECEPTION, label: chambres}

    admin.categorieChambre:
        class: Indra\AdminBundle\Admin\CategorieChambreAdmin
        arguments: [~, Indra\AdminBundle\Entity\CategorieChambre, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: RECEPTION, label: Categories}

    admin.gallery:
        class: Indra\AdminBundle\Admin\GalleryAdmin
        arguments: [~, Indra\AdminBundle\Entity\Gallery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: GALLERY & MEDIA, label: Gallery}

    admin.image:
        class: Indra\AdminBundle\Admin\ImageAdmin
        arguments: [~, Indra\AdminBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: GALLERY & MEDIA, label: Images}

    admin.reservation:
        class: Indra\AdminBundle\Admin\ReservationAdmin
        arguments: [~, Indra\AdminBundle\Entity\Reservation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: RECEPTION, label: Reservation}

    admin.articleBlog:
        class: Indra\AdminBundle\Admin\ArticleAdmin
        arguments: [~, Indra\AdminBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: BLOG, label: Article}

#    admin.tourisme:
#        class: Indra\AdminBundle\Admin\TourismeAdmin
#        arguments: [~, Indra\AdminBundle\Entity\Tourisme, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: Tourisme, label: Tourisme}



#mes services personnalisées


    projet.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: projet_client_registration }

    projet.changePassword.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ChangePasswordFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: projet_client_changePassword }
    projet.editProfile.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: projet_client_profile_edit }


#   Mes services Personnelles

    projet.search:
        class : Indra\AdminBundle\Services\Search
        arguments: ["@doctrine.orm.entity_manager", "@request_stack" ]
        scope: "request"

    application.operation:
        class : Indra\AdminBundle\Services\OperationApp
        arguments: ["@doctrine.orm.entity_manager", "@request_stack" ]
        scope: "request"


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
