client_informations:
    path:     /client
    defaults: { _controller: IndraAdminBundle:Client:index }


client_create:
    path:     /client/create
    defaults: { _controller: IndraAdminBundle:Client:create }

client_edit:
    path:     /client/{id}
    defaults: { _controller: IndraAdminBundle:Client:edit }


client_delete:
    path:     /client/delete/{id}/{del}
    defaults: { _controller: IndraAdminBundle:Client:delete, _locale : fr }
    options:
        expose: true


client_update:
    path:     /client/{id}/
    defaults: { _controller: IndraAdminBundle:Client:update }


