contrat_create:
    path:     /contrat/create
    defaults: { _controller: IndraAdminBundle:Contrat:create }

contrat_show:
    path:     /contrat/{id}
    defaults: { _controller: IndraAdminBundle:Contrat:show }


contrat_delete:
    path:     /contrat/delete/{id}/{del}
    defaults: { _controller: IndraAdminBundle:Contrat:delete, _locale : fr}
    options:
        expose: true

contrat_edit:
    path:     /contrat/{id}/edit/{idEmploye}
    defaults: { _controller: IndraAdminBundle:Contrat:edit }

contrat_update:
    path:     /contrat/{id}/
    defaults: { _controller: IndraAdminBundle:Contrat:update }


contrat_print:
    path:     /contrat/{id}/{idEmploye}
    defaults: { _controller: IndraAdminBundle:Contrat:print }

contrat_checkDate:
    path:     /contrat/check/date/{idEmploye}
    defaults: { _controller: IndraAdminBundle:Contrat:checkDate, _locale : fr }
    options:
        expose: true

