data_informations:
    path:     /data
    defaults: { _controller: IndraAdminBundle:Data:index }

data_create:
    path:     /data/create
    defaults: { _controller: IndraAdminBundle:Data:create }

data_edit:
    path:     /data/edit/{id}
    defaults: { _controller: IndraAdminBundle:Data:edit }

data_update:
    path:     /data/{id}/
    defaults: { _controller: IndraAdminBundle:Data:update }

data_delete:
    path:     /data/delete/{id}/{del}
    defaults: { _controller: IndraAdminBundle:Data:delete, _locale : fr}
    options:
        expose: true