demandepermission_create:
    path:     /demandepermission/create
    defaults: { _controller: IndraAdminBundle:DemandePermission:create }

demandepermission_show:
    path:     /demandepermission/{id}
    defaults: { _controller: IndraAdminBundle:DemandePermission:show }

demandepermission_valid:
    path:     /demandepermission/{id}/{valid}/{idEmploye}
    defaults: { _controller: IndraAdminBundle:DemandePermission:valid }

demandepermission_update:
    path:     /demandepermission/{id}/
    defaults: { _controller: IndraAdminBundle:DemandePermission:update }

demandepermission_checkDate:
    path:     /demandepermissioncheckDate/{idEmploye}
    defaults: { _controller: IndraAdminBundle:DemandePermission:checkDate, _locale : fr }
    options:
        expose: true

demandepermission_print:
    path:     /demandepermission/{id}/{idEmploye}
    defaults: { _controller: IndraAdminBundle:DemandePermission:print }