facturereception_informations:
    path:     /factureReception
    defaults: { _controller: IndraAdminBundle:FactureReception:index }

facturereception_create:
    path:     /factureReception/create
    defaults: { _controller: IndraAdminBundle:FactureReception:create }

facturereception_show:
    path:     /factureReception/{id}
    defaults: { _controller: IndraAdminBundle:FactureReception:show }

facturereception_delete:
    path:     /factureReception/delete/{id}/{del}
    defaults: { _controller: IndraAdminBundle:FactureReception:delete, _locale : fr}
    options:
        expose: true

facturereception_update:
    path:     /factureReception/{id}/
    defaults: { _controller: IndraAdminBundle:FactureReception:update }


facturereception_valid:
    path:     /factureReception/{id}/{valid}
    defaults: { _controller: IndraAdminBundle:FactureReception:valid }