materiel_create:
    path:     /materiel/create
    defaults: { _controller: IndraAdminBundle:Materiel:create }

materiel_show:
    path:     /materiel/{id}
    defaults: { _controller: IndraAdminBundle:Materiel:show }

materiel_update:
    path:     /materiel/{id}/
    defaults: { _controller: IndraAdminBundle:Materiel:update }

materiel_print:
    path:     /materiel/{id}/{idEmploye}
    defaults: { _controller: IndraAdminBundle:Materiel:print }

materiel_checkDate:
    path:     /materielcheckDate/{idEmploye}
    defaults: { _controller: IndraAdminBundle:Materiel:checkDate, _locale : fr }
    options:
        expose: true

materiel_checkQte:
    path:     /materielcheckQte/{idStock}
    defaults: { _controller: IndraAdminBundle:Materiel:checkQte}
    options:
        expose: true