periodestock_informations:
    path:     /periodestock/{idStock}/{idTypeStock}
    defaults: { _controller: IndraAdminBundle:PeriodeStock:index }

periodestock_create:
    path:     /periodestockcreate/create
    defaults: { _controller: IndraAdminBundle:PeriodeStock:create }

periodestock_edit:
    path:     /periodestock/{id}/{idStock}/{idTypeStock}
    defaults: { _controller: IndraAdminBundle:PeriodeStock:edit }

periodestock_update:
    path:     /periodestock/{id}/
    defaults: { _controller: IndraAdminBundle:PeriodeStock:update }

periodestock_checkDate:
    path:     /periodestockcheckDate/{idEmploye}
    defaults: { _controller: IndraAdminBundle:PeriodeStock:checkDate, _locale : fr }
    options:
        expose: true

periodestock_delete:
    path:     /periodestockdel/delete/{id}/{del}/{idRefresh}/{idRefresh2}
    defaults: { _controller: IndraAdminBundle:PeriodeStock:delete, _locale : fr}
    options:
        expose: true

