poste_informations:
    path:     /poste
    defaults: { _controller: IndraAdminBundle:Poste:index }


poste_create:
    path:     /poste/create
    defaults: { _controller: IndraAdminBundle:Poste:create }

poste_show:
    path:     /poste/{id}
    defaults: { _controller: IndraAdminBundle:Poste:show }


poste_delete:
    path:     /poste/delete/{id}/{del}
    defaults: { _controller: IndraAdminBundle:Poste:delete, _locale : fr}
    options:
        expose: true

poste_edit:
    path:     /poste/{id}/edit
    defaults: { _controller: IndraAdminBundle:Poste:edit }

poste_update:
    path:     /poste/{id}/
    defaults: { _controller: IndraAdminBundle:Poste:update }

poste_of_service:
    path:     /poste/service/{id}/
    defaults: { _controller: IndraAdminBundle:Poste:servicePoste, _locale : fr }
    options:
        expose: true