presence_create:
    path:     /presence/create
    defaults: { _controller: IndraAdminBundle:Presence:create }

presence_show:
    path:     /presence/{id}
    defaults: { _controller: IndraAdminBundle:Presence:show }


presence_delete:
    path:     /presence/delete/{id}/{del}
    defaults: { _controller: IndraAdminBundle:Presence:delete, _locale : fr }
    options:
        expose: true

presence_edit:
    path:     /presence/{id}/edit/{idEmploye}
    defaults: { _controller: IndraAdminBundle:Presence:edit }

presence_update:
    path:     /presence/{id}/
    defaults: { _controller: IndraAdminBundle:Presence:update }


presence_checkFile:
    path:     /presence/check/{file}/
    defaults: { _controller: IndraAdminBundle:Presence:checkFile, _locale : fr }
    options:
        expose: true

presence_checkDate:
    path:     /presence/check/date/{idEmploye}
    defaults: { _controller: IndraAdminBundle:Presence:checkDate, _locale : fr }
    options:
        expose: true
