reunion_informations:
    path:     /reunion
    defaults: { _controller: IndraAdminBundle:Reunion:index }

reunion_create:
    path:     /reunion/create
    defaults: { _controller: IndraAdminBundle:Reunion:create }


reunion_delete:
    path:     /reunion/delete/{id}/{del}
    defaults: { _controller: IndraAdminBundle:Reunion:delete, _locale : fr }
    options:
        expose: true

reunion_show:
    path:     /reunion/{id}
    defaults: { _controller: IndraAdminBundle:Reunion:show }

reunion_update:
    path:     /reunion/update/{id}
    defaults: { _controller: IndraAdminBundle:Reunion:update }

reunion_checkDate:
    path:     /reunioncheckDate/{idEmploye}
    defaults: { _controller: IndraAdminBundle:Reunion:checkDate, _locale : fr }
    options:
        expose: true
