service_informations:
    path:     /service
    defaults: { _controller: IndraAdminBundle:Service:index }


service_create:
    path:     /service/create
    defaults: { _controller: IndraAdminBundle:Service:create }

service_delete:
    path:     /service/delete/{id}/{del}
    defaults: { _controller: IndraAdminBundle:Service:delete, _locale : fr }
    options:
        expose: true

service_edit:
    path:     /service/{id}/edit
    defaults: { _controller: IndraAdminBundle:Service:edit }

service_update:
    path:     /service/{id}/
    defaults: { _controller: IndraAdminBundle:Service:update }