stock_informations:
    path:     /stock
    defaults: { _controller: IndraAdminBundle:Stock:index }

stock_create:
    path:     /stock/create
    defaults: { _controller: IndraAdminBundle:Stock:create }

stock_show:
    path:     /stock/{id}
    defaults: { _controller: IndraAdminBundle:Stock:show }

stock_edit:
    path:     /stock/{id}/{idTypeStock}
    defaults: { _controller: IndraAdminBundle:Stock:edit }

stock_update:
    path:     /stock/{id}/
    defaults: { _controller: IndraAdminBundle:Stock:update }

stock_delete:
    path:     /stock/delete/{id}/{del}/{idRefresh}
    defaults: { _controller: IndraAdminBundle:Stock:delete, _locale : fr }
    options:
        expose: true
