<?php

namespace Indra\AdminBundle\Entity\Repository;

/**
 * FactureReceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureReceptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGroupDateBuilder(){

        $qb =  $this->createQueryBuilder('f')
                    ->groupBy('f.updatedAt')
        ;
//        var_dump($qb->getQuery());
        return $qb->getQuery()->getResult();
    }
}
