<?php

namespace Indra\AdminBundle\Entity\Repository;

/**
 * FactureReceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureReceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
